// import Head from 'next/head';
// import NavBar from '../components/NavBar/NavBar';
// import CardProgres from '../components/Cards/CardProgres';
// import styles from '../styles/Home.module.css'
// import CardVideo from '../components/Cards/CardVideo';
// import React, { useEffect, useState } from 'react';
// import CardHero from '../components/Cards/CardHero';
// import  getMarvelData  from '../js/marvel-api';
// import arrow from '../assets/arrow.png'
// import Image from 'next/image';
// import Footer from '../components/Footer/Footer';

// export default function Home() {
//   const [marvelData, setMarvelData] = useState([]);
//   const [pageNumber, setPageNumber] = useState(0);
//   const [pageSize, setPageSize] = useState(10);
//   const numPage = (pageNumber+10).toString().slice(0,-1)

//   useEffect(() => {
//     async function fetchData() {
//       const data = await getMarvelData(pageNumber, pageSize);
//       setMarvelData(data);
//     }
//     fetchData();
//   }, [pageNumber, pageSize]);
  
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>DCORP</title>
//         <meta name="List the characters of the marvel universe" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <NavBar />
//       <div className={styles.card}>
//         <CardProgres />
//         <CardVideo videoUrl="https://www.youtube.com/embed/ctcQ6b037k0"/>
//         <CardVideo />
//       </div>
//       <div className={styles.card}>
//           {marvelData.map((dato, index) => (
//             console.log(dato),
//             <CardHero key={index} name={dato.name} comics={dato.comics.available} image={`${dato.thumbnail.path}.${dato.thumbnail.extension}`} movies={dato.stories.available}/>
//           ))}
//       </div>
//       <div className={styles.pagination}>
//             <button className={styles.left} onClick={() => setPageNumber(pageNumber - 10)} disabled={pageNumber === 0}>
//               <Image className={styles.arrow} src={arrow} alt='arrow'/>
//             </button>
//             <p className={styles.page}>{numPage}/{pageSize}</p>
//             <button className={styles.rigth} onClick={() => setPageNumber(pageNumber + 10)}>
//               <Image className={styles.arrowRigth} src={arrow} alt='arrow'/>
//             </button>
//         </div>
//       <Footer />  
//     </div>
//   )
// }

import Head from 'next/head';
import NavBar from '../components/NavBar/NavBar';
import CardProgres from '../components/Cards/CardProgres';
import styles from '../styles/Home.module.css'
import CardVideo from '../components/Cards/CardVideo';
import React, { useEffect, useState } from 'react';
import CardHero from '../components/Cards/CardHero';
import getMarvelData from '../js/marvel-api';
import arrow from '../assets/arrow.png'
import Image from 'next/image';
import Footer from '../components/Footer/Footer';

export default function Home() {
  const [marvelData, setMarvelData] = useState([]);
  const [pageNumber, setPageNumber] = useState(0);
  const [pageSize, setPageSize] = useState(10);
  const [isLoading, setIsLoading] = useState(false); // Estado para el loader
  const numPage = (pageNumber+10).toString().slice(0,-1)

  useEffect(() => {
    async function fetchData() {
      setIsLoading(true); // Se activa el loader
      const data = await getMarvelData(pageNumber, pageSize);
      setMarvelData(data);
      setIsLoading(false); // Se desactiva el loader
    }
    fetchData();
  }, [pageNumber, pageSize]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>DCORP</title>
        <meta name="List the characters of the marvel universe" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {isLoading && <div className={styles.loader}>Cargando...</div>}  {/*Loader */}
      <div className={styles.card}>
        <CardProgres />
        <CardVideo videoUrl="https://www.youtube.com/embed/ctcQ6b037k0"/>
        <CardVideo />
      </div>
      <div className={styles.card}>
          {marvelData.map((dato, index) => (
            console.log(dato),
            <CardHero key={index} name={dato.name} comics={dato.comics.available} image={`${dato.thumbnail.path}.${dato.thumbnail.extension}`} movies={dato.stories.available}/>
          ))}
      </div>
      <div className={styles.pagination}>
            <button className={styles.left} onClick={() => setPageNumber(pageNumber - 10)} disabled={pageNumber === 0}>
              <Image className={styles.arrow} src={arrow} alt='arrow'/>
            </button>
            <p className={styles.page}>{numPage}/{pageSize}</p>
            <button className={styles.rigth} onClick={() => setPageNumber(pageNumber + 10)}>
              <Image className={styles.arrowRigth} src={arrow} alt='arrow'/>
            </button>
        </div>
      <Footer />  
    </div>
  )
}
